In [2]:
!pip install -q tensorflow

     |████████████████████████████████| 462 kB 8.3 MB/s 


In [3]:
import tensorflow
print(tensorflow.__version__)

2.8.0


In [5]:
from tensorflow.keras.layers import Input,SimpleRNN,Flatten,Dense
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.models import Model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
N = 1 # number of samples
T = 10 # number of time sequence
D = 3 # number of features
M = 5 # number of hidden layers
K = 2 # number of output

In [7]:
X = np.random.randn(N,T,D)

In [9]:
X.shape

(1, 10, 3)

In [10]:
i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [12]:
y_hat = model.predict(X)
y_hat[0]

array([-0.10450526,  0.8865529 ], dtype=float32)

In [17]:
model.layers[1].get_weights()

[array([[-0.17267859,  0.4604543 ,  0.85265666, -0.06709206, -0.67042005],
        [ 0.31811637,  0.71139985, -0.3151338 ,  0.80920845, -0.02812952],
        [-0.14834762,  0.20954853, -0.22784585, -0.3542797 , -0.05022603]],
       dtype=float32),
 array([[-0.88420475,  0.2708631 , -0.06236813, -0.25947645,  0.27128842],
        [ 0.06429033,  0.8606136 ,  0.1187996 ,  0.16858412, -0.4611689 ],
        [ 0.00486899,  0.03321535,  0.913893  ,  0.17817049,  0.36321935],
        [ 0.24504839,  0.34920767, -0.37767068,  0.38136998,  0.727961  ],
        [ 0.3923982 ,  0.2508543 ,  0.06451099, -0.8526803 ,  0.22775076]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [18]:
Wx, Wh, bh = model.layers[1].get_weights()  # Wx: input to hidden layer; Wh: hidden to hidden layer; bh: bias

In [19]:
Wo, bo = model.layers[2].get_weights()   #Wo: hidden to output layer weights; bo: bias 

In [20]:
h_last = np.zeros(M)
y_pred = []
x = X[0]

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo
  y_pred.append(y)

  h_last = h  # capture the last hidden layer information


In [21]:
y_pred[-1]

array([-0.10450523,  0.88655296])