In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
data = pd.read_csv("Churn_Modelling.CSV")
print(data.shape)

(10000, 14)


In [3]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
data.drop(["RowNumber","CustomerId","Surname"], axis=1, inplace=True)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data.Gender = le.fit_transform(data.Gender)

In [6]:
data.Gender

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64

In [7]:
data = pd.get_dummies(data)

In [8]:
data.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited',
       'Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype='object')

In [9]:
data.head()

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                  0                0
1          608       0  ...                  0                1
2          502       0  ...                  0                0
3          699       0  ...                  0                0
4          850       0  ...                  0                1

[5 rows x 13 columns]

In [10]:
X = data.drop("Exited", axis=1).values
Y = data.Exited.values

In [11]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(X,Y, test_size =0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

ANN Model

In [13]:
ann = tf.keras.Sequential()       # Building an ANN onbject

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  # Adding input layer and one hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  # Adding second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  # Adding output layer

In [17]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])  #Compiling the ANN model

In [18]:
ann.fit(xtrain,ytrain, batch_size=32, epochs=100)   #Training the model

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6504 - accuracy: 0.6607
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5074 - accuracy: 0.7955
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4522 - accuracy: 0.8016
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4251 - accuracy: 0.8123
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4079 - accuracy: 0.8190
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3950 - accuracy: 0.8298
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3849 - accuracy: 0.8344
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3779 - accuracy: 0.8374
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3728 - accuracy: 0.8386
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3686 - accura

In [19]:
ypred = ann.predict(xtest)
ypred = (ypred > 0.5)
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [20]:
ypred = ypred.flatten()
ypred

array([False, False, False, ..., False, False, False])

In [21]:
ypred = ypred.astype(int)
ypred

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix
matrix = confusion_matrix(ytest,ypred)
matrix

array([[1504,   91],
       [ 193,  212]])

In [23]:
accuracy_score(ytest,ypred)

0.858

In [24]:
ann1 = tf.keras.Sequential()       # Building an ANN onbject

In [25]:
ann1.add(tf.keras.layers.Dense(units=6, activation='relu'))  # Adding input layer and one hidden layer

In [26]:
ann1.add(tf.keras.layers.Dense(units=6, activation='relu'))  # Adding second hidden layer

In [27]:
ann1.add(tf.keras.layers.Dense(units=6, activation='relu'))  # Adding third hidden layer

In [28]:
ann1.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  # Adding output layer

In [29]:
ann1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])  #Compiling the ANN model

In [30]:
ann1.fit(xtrain,ytrain, batch_size=32, epochs=100)   #Training the model

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5141 - accuracy: 0.7954
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4658 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4517 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4423 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4346 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4285 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4243 - accuracy: 0.7969
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4188 - accuracy: 0.8139
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4076 - accuracy: 0.8241
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3954 - accura

In [31]:
ypred1 = ann1.predict(xtest)
ypred1 = (ypred1 > 0.5).flatten().astype(int)
ypred1

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix
matrix = confusion_matrix(ytest,ypred1)
matrix

array([[1516,   79],
       [ 197,  208]])

In [33]:
accuracy_score(ytest,ypred1)

0.862

In [34]:
ann2 = tf.keras.models.Sequential()

In [35]:
ann2.add(tf.keras.layers.Dense(units= 10, activation= "relu")) # input and 1st layer

In [36]:
ann2.add(tf.keras.layers.Dense(units= 10, activation= "relu")) # 2nd layer

In [37]:
ann2.add(tf.keras.layers.Dense(units= 10, activation= "relu")) # 3rd layer

In [38]:
ann2.add(tf.keras.layers.Dense(units= 1, activation= "sigmoid")) # output layer

In [39]:
ann2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])  #Compiling the ANN model

In [40]:
ann2.fit(xtrain,ytrain, batch_size=32, epochs=100)   #Training the model

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6148 - accuracy: 0.6825
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4706 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4451 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4335 - accuracy: 0.8029
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4274 - accuracy: 0.8080
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4224 - accuracy: 0.8154
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4165 - accuracy: 0.8176
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.8278
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3977 - accuracy: 0.8351
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3819 - accura

In [41]:
ypred2 = ann1.predict(xtest)
ypred2 = (ypred2 > 0.5).flatten().astype(int)
ypred2

array([0, 0, 0, ..., 0, 0, 0])

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix
matrix = confusion_matrix(ytest,ypred2)
matrix

array([[1516,   79],
       [ 197,  208]])

In [43]:
accuracy_score(ytest,ypred2)

0.862